### ISSUE TITLE
v0.1.0 Roadmap

### ISSUE THREAD

**Issue by dieghernan** [dieghernan/cffr#5]
# Overall

-   [x] Create [codemeta.json](https://github.com/ropensci/codemetar) file.
-   [x] Packages should run on all major platforms (Windows, macOS, Linux).
-   [x] Consider an `object_verb()` naming scheme.
-   [x] We strongly recommend `snake_case.`
-   [x] Use [`message()`](https://rdrr.io/r/base/message.html) and [`warning()`](https://rdrr.io/r/base/warning.html) to communicate with the user in your functions. Please do not use [`print()`](https://rdrr.io/r/base/print.html) or [`cat()`](https://rdrr.io/r/base/cat.html) unless it's for a `print.*()` or `str.*()` methods.
-   [x] We recommend the [`styler` package](https://github.com/r-lib/styler) for automating part of the code styling.
-   [x] Add a code of conduct and contribution guidelines, cf [this section of the book](https://devguide.ropensci.org/collaboration.html#friendlyfiles).

# README

-   [x] Use Active [repostatus.org badge](https://www.repostatus.org/).

-   From top to bottom

    -   [x] The package name

    -   [x] Badges for continuous integration and test coverage, the badge for rOpenSci peer-review once it has started (see below), a repostatus.org badge, and any other badges.

    -   [x] Short description of goals of package, with descriptive links to all vignettes (rendered).

    -   [x] Installation instructions

    -   [ ] ~~Any additional setup required (authentication tokens, etc)~~

    -   [x] Brief demonstration usage

    -   [x] If applicable, how the package compares to other similar packages and/or how it relates to other packages

    -   [x] Citation information

# Vignettes
 
 - [x] Vignette 1: Manipulating `cff` objects
 - [x] Vignette 2: Crosswalk 
 
 # TODO
 - [x] Custom GH Action for creating CITATION.cff files

**Comment by dieghernan** [comment]
#14
